version: "3.8"

services:
  clienthub:
    tty: true
    stdin_open: true
    container_name: "clientreact"
    image: react:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    command: npm start